title: tylermac.net
subtitle: null
description: null
author: Tyler MacLeod
timezone: null
url: 'http://tylermac.github.io'
root: /
permalink: ':category/:title/'
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: draft
titlecase: false
external_link: false
filename_case: 1
render_drafts: false
post_asset_folder: true
relative_link: false
future: false
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: null
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
per_page: 10
pagination_dir: page
theme: minos
deploy:
  type: git
  repo: 'git@github.com:tylermac/tylermac.github.io.git'
feed:
  type: rss2
  path: rss2.xml
alias:
  feed/: rss2.xml
category_generator:
  per_page: 20
language: en
# Header
logo_text: Tyermac.Net # Add text logo instead of logo image
menu:
  Home: /
  Categories: categories
  Tags: tags
  Archives: archives
  
# Content
excerpt_link: Read More
toc         : true #  Whether to show the table of contents in articles
fancybox    : false

# Miscellaneous
google_analytics:
favicon: /favicon.png

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-deflist
    - markdown-it-smartarrows
  anchors:
    level: 2
    collisionSuffix: 'v'
    permalink: false
    permalinkClass: header-anchor
    permalinkSymbol: §